swagger: '2.0'
info:
  title: "Human Services Data Taxonomy API"
  description: "This is a complimentary API to the HSDA API focusing just on taxonomy."
  termsOfService: "https://openreferral.org/documentation/"
  contact:
    name: Open Referral
    url: https://openreferral.org/
    email: info@openreferral.org
  license:
    name: Open Data Commons Public Domain
    url: http://opendatacommons.org/licenses/pddl/
  version: v1.2
host: hsda.taxonomy.api.adopta.agency
basePath: /
schemes:
- http
produces:
- application/json
paths:
  /taxonomy/:
    get:
      summary: Get Taxonomy
      description: Get Taxonomy
      operationId: listTaxonomy
      security:
        - appid: []
        - appkey: []      
      responses:
        '200':
          description: Item Response
          schema:
            type: array
            items:
              $ref: "#/definitions/taxonomy"
      tags:
      - Taxonomy
securityDefinitions:
  appid:
    type: apiKey
    in: header
    name: x-appid
  appkey:
    type: apiKey
    in: header
    name: x-appkey
definitions:
  taxonomy:
    properties:
      id:
        description: 'Each entry must have a unique identifier.'
        type: string
    required:
      - id
